services: {}
  # test:
  #   image: hello:123
  #   labels:
  #     kompose.tolerations: sku=gpu:NoSchedule;key=value:NoSchedule
  #     kompose.nodeSelectors: test=hello
  #     kompose.replicas: 1
  #     kompose.service.group: hello
  #   environment:
  #     WORDPRESS_DB_PASSWORD_FILE: /run/secrets/test
  #     WORDPRESS_DB_PASSWORD_CONFIG: /test
  #   ports: 
  #     - 8080:8080
  # test2:
  #   image: hello:321
  #   labels:
  #     kompose.tolerations: sku=gpu:NoSchedule;key=value:NoSchedule
  #     kompose.nodeSelectors: test=hello
  #     kompose.replicas: 1
  #     kompose.service.group: hello
  #   ports: 
  #     - 8181:8181
  # another:
  #   image: test:123
  #   environment:
  #     WORDPRESS_DB_PASSWORD_FILE: /test
  #   configs:
  #     - test
  #   volumes:
  #     - test:/var/lib/backup/data

# secrets:
#   my_secret:
#     file: /tmp/hello.txt

config: {}
  # test:
  #   content: ""

volumes: {}
  # test:
  #   name: persistentVolumeClaim
  #   labels:
  #     - "claimName=hello"

# x-externalSecrets:
  # secretStoreName: 
  # secretStoreKind:
