{{- range $app, $config := .Values.apps }}
{{- $type := (default $.Values.defaultRepoType $config.type) }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $app }}
  namespace: {{ default $.Release.Namespace $config.namespace }}
spec:
  interval: {{ default "5m" $config.interval }}
  install:
    createNamespace: true
  chart:
    spec:
      chart: {{ default $app $config.path }}
      {{- if eq $type "HelmRepository" }}
      version: {{ required "Please provide a version for the helm chart" $config.version }}
      {{- end }}
      sourceRef:
        kind: {{ $type }}
        name: {{ required "Please provide name of the repository" $config.repo }}
        namespace: {{ default $.Release.Namespace $config.namespace }}
      interval: {{ default "5m" $config.interval }}
  {{- with $config.valuesFrom }}
  valuesFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $config.valuesInline }}
  values:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
