{{- range $app, $config := .Values.apps }}
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ $app }}
  namespace: {{ default $.Release.Namespace $.Values.fluxNamespace }}
spec:
  interval: {{ default "5m" $config.interval }}
  chart:
    spec:
      chart: {{ $app }}
      {{- if eq $config.type "HelmRepository" }}
      version: {{ required "Please provide a version for the helm chart" $config.version }}
      {{- end }}
      sourceRef:
        kind: {{ default "HelmRepository" $config.type }}
        name: {{ required "Please provide name of the repository" $config.repo }}
        namespace: {{ default $.Release.Namespace $config.namespace }}
      interval: {{ default "5m" $config.interval }}
  {{- with $config.valuesInline }}
  values:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
