{{- range $repo, $config := .Values.repositories }}
{{- $kind := (default "HelmRepository" $config.kind) }}
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: {{ $kind }}
metadata:
  name: {{ $repo }}
spec:
  {{- if eq "HelmRepository" $kind }}
  type: {{ default "" $config.type }}
  {{- end }}
  interval: {{ default "5m" $config.interval }}
  url: {{ required "Please provide a URL for the repository" $config.url }}
  {{- if or (eq $config.type "git") (eq $kind "GitRepository") }}
  ref:
    branch: {{ default "main" $config.branch }}
  {{- end }}
  {{- with $config.repoAccessSecret }}
  secretRef:
    name: {{ . }}
  {{- end }}
{{- end }}
