{{- $es := index .Values "x-externalSecrets" }}
{{- range $key, $config := .Values.secrets }}
---
{{- if $config.external }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $key }}
  labels:
    {{- include "kompose.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ required "Please provide external secret secretStoreName" $es.secretStoreName }}
    kind: {{ default "ClusterSecretStore" $es.secretStoreKind }}

  refreshInterval: {{ default "1h" $es.refreshInterval }}

  target:
    name: {{ $key }}

  # Data defines the connection between the Kubernetes Secret keys and the Provider data
  data:
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $key }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  labels:
    {{- include "kompose.labels" $ | nindent 4 }}
data:
  {{- toYaml (dict $key ($.Files.Get $config.file | b64enc)) | nindent 2 }}
{{- end }}
{{- end }}