{{- range $secret, $config := .Values.azureKeyVault.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret }}
  namespace: {{ default "default" $config.namespace }}
spec:
  refreshInterval: {{ $.Values.secretRefreshInterval }}
  secretStoreRef:
    kind: {{ $.Values.secretStoreType }}
    name: azure-key-vault

  target:
    name: {{ $secret }}
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  {{- range $secret := $config.keys }}
  - secretKey: {{ $secret.secretKey }}
    remoteRef:
      key: {{ $secret.akvKey }}
  {{- end }}
{{- end }}
{{- range $secret, $config := .Values.vault.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret }}
  namespace: {{ default "default" $config.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: {{ $.Values.secretStoreType }}
    name: vault

  target:
    name: {{ $secret }}
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  {{- range $secret := $config.keys }}
  - secretKey: {{ $secret.secretKey }}
    remoteRef:
      key: {{ $secret.path }}
      property: {{ $secret.property }}
  {{- end }}
{{- end }}